# Generated by Django 2.0.4 on 2018-05-25 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Thumbnail',
            field=models.ImageField(default='defaults/default_blog.png', upload_to=''),
        ),
    ]
