# Generated by Django 2.0.4 on 2018-05-25 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_app', '0002_post_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Thumbnail',
            new_name='thumbnail',
        ),
    ]
