# Generated by Django 2.0.4 on 2018-05-11 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='static/Images/Avatar/default.jpg', null=True, upload_to='user_avatar'),
        ),
    ]
