# Generated by Django 2.0.4 on 2018-05-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0004_auto_20180510_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='defaults/default_avatar.jpg', null=True, upload_to='user_avatar'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='banner',
            field=models.ImageField(blank=True, default='defaults/default_banner.png', null=True, upload_to='user_banner'),
        ),
    ]
