# Generated by Django 2.0.4 on 2018-06-24 03:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scholarship_map', '0003_auto_20180614_2248'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SchoolSports',
            new_name='School_Sports',
        ),
        migrations.RenameModel(
            old_name='SportStats',
            new_name='Sport_Stats',
        ),
        migrations.RenameModel(
            old_name='UserSchools',
            new_name='User_Schools',
        ),
        migrations.RenameModel(
            old_name='UserSports',
            new_name='User_Sports',
        ),
        migrations.AlterModelOptions(
            name='school_sports',
            options={'verbose_name_plural': 'SchoolSports'},
        ),
        migrations.AlterModelOptions(
            name='schools',
            options={'verbose_name_plural': 'Schools'},
        ),
        migrations.AlterModelOptions(
            name='sport_stats',
            options={'verbose_name_plural': 'Sports_Stats'},
        ),
        migrations.AlterModelOptions(
            name='sports',
            options={'verbose_name_plural': 'Sports'},
        ),
        migrations.AlterModelOptions(
            name='user_schools',
            options={'verbose_name_plural': 'User_Schools'},
        ),
        migrations.AlterModelOptions(
            name='user_sports',
            options={'verbose_name_plural': 'User_Sports'},
        ),
    ]
