# Generated by Django 2.0.4 on 2018-06-24 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship_map', '0004_auto_20180623_2334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school_sports',
            options={'verbose_name_plural': 'School_Sports'},
        ),
    ]
